Settings:
  defaultSpeed: 1.0
Messages:
  WinMessage: '&aYou won the jump!'
  LoseMessage: '&cYou lost the jump!'
  PrepareToJump: '&bPREPARE TO START!'
  PrepareToStart: "&7The game will begin through"
  NotAPlayerMessage: '&cYou must be a Player to do that!'
  NoPermissionMessage: '&cInsufficient permissions.'
  AttemptJoinMessage: '&aAttempting to join a jump arena...'
  JoinedMessage: '&aSuccessfully joined <arena>!'
  IncorrectArgsMessage: '&cIncorrect args! Try &e/fjump help'
  CreateKitMessage: '&aSuccessfully created the kit called &e<kit>&a!'
  NoKitByThatNameMessage: '&cThere is no kit called &e<kit>&c!'
  SelectKitMessage: '&aSelected &e<kit>&a!'
  DeleteKitMessage: '&aSuccessfully deleted &e<kit>&a!'
  CreateArenaMessage: '&aSuccessfully created an arena! Do not forget to set platforms and failZone!'
  NoArenaByThatNameMessage: '&cThere is no arena called &e<arena>&c!'
  ThatArenaIsFullMessage: '&cThat arena is not available right now! (It is start already)'
  AlreadyInArenaMessage: '&cYou are already in a arena! You cannot join another one yet. Finish your current arena first!'
  NotInArenaMessage: '&cYou are not in a jump arena, so you cannot leave one!'
  LeftArenaMessage: '&aYou left the arena.'
  CannotLeaveArenaMessage: '&cThe arena has already started! You cannot leave now!'
Arenas: